#
# This software is contributed or developed by KYOCERA Corporation.
# (C) 2011 KYOCERA Corporation
#
# Makefile for the Linux IrDA infrared PM device drivers.
#
# 20 April 2011, 

obj-y			+= irdaeg.o

irdaeg-objs		:= irda_eg.o
