#
# This software is contributed or developed by KYOCERA Corporation.
# (C) 2011 KYOCERA Corporation
#
# Makefile for the Linux IrDA infrared PM device drivers.
#
# 20 April 2011, 

obj-y			+= irdaeg2.o

irdaeg2-objs		:= irda_eg2.o
