#
# This software is contributed or developed by KYOCERA Corporation.
# (C) 2011 KYOCERA Corporation
#
# Makefile for the Linux IrDA infrared PM device drivers.
#
# 20 April 2011, 

obj-y			+= irdaeg1.o

irdaeg1-objs		:= irda_eg1.o
